controller_manager:
  ros__parameters:

    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    carriage_controller:
      type: velocity_controllers/JointGroupVelocityController


#joint_state_broadcaster:
#  ros__parameters:


diff_drive_controller:
  ros__parameters:

    left_wheel_names:
      - left_drive

    right_wheel_names:
      - right_drive

    wheel_separation: 0.60
    wheel_radius: 0.15  

    publish_rate: 50.0

    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true

    use_stamped_vel: false
    cmd_vel_timeout: 0.5

    publish_limited_velocity: true
    open_loop: false
    velocity_rolling_window_size: 10

carriage_controller:
  ros__parameters:

    joints:
      - carriage

    interface_name: velocity
